{"uid":"737e0c26c4146cf7","name":"Оформление экскурсии","fullName":"tests.test_excursium.TestUserCases#test_order_excursion","historyId":"8dbe8db0514bd0080803b2e3e65bae34","time":{"start":1753362226793,"stop":1753362241508,"duration":14715},"description":"Переход с главной страницы к экскурсиям с дальнейшим оформлением одной из них (юзер-сценарий)","descriptionHtml":"<p>Переход с главной страницы к экскурсиям с дальнейшим оформлением одной из них (юзер-сценарий)</p>\n","status":"broken","statusMessage":"selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (1439, -2090)\n  (Session info: chrome=138.0.7204.168); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#elementclickinterceptedexception\nStacktrace:\n#0 0x5614760e670e <unknown>\n#1 0x561475b82a51 <unknown>\n#2 0x561475bd3701 <unknown>\n#3 0x561475bd1cb9 <unknown>\n#4 0x561475bcf851 <unknown>\n#5 0x561475bcefe3 <unknown>\n#6 0x561475bc391a <unknown>\n#7 0x561475bf0ff2 <unknown>\n#8 0x561475bc30fd <unknown>\n#9 0x561475bf11be <unknown>\n#10 0x561475c10444 <unknown>\n#11 0x561475bf0dc3 <unknown>\n#12 0x561475bc1959 <unknown>\n#13 0x561475bc24c1 <unknown>\n#14 0x5614760b28aa <unknown>\n#15 0x5614760b5c11 <unknown>\n#16 0x5614760b56a8 <unknown>\n#17 0x5614760b60b5 <unknown>\n#18 0x56147609c34c <unknown>\n#19 0x5614760b6421 <unknown>\n#20 0x561476084e2a <unknown>\n#21 0x5614760d4855 <unknown>\n#22 0x5614760d4a4e <unknown>\n#23 0x5614760e59f5 <unknown>\n#24 0x7f01536431c4 <unknown>","statusTrace":"self = <test_excursium.TestUserCases object at 0x7fb1cfc04f50>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"a32448e15551abdbd4cd438c3c21f3d7\")>\n\n    @allure.title(\"Оформление экскурсии\")\n    @allure.severity(\"Critical\")\n    @pytest.mark.user_case\n    def test_order_excursion(self, driver):\n        \"\"\"Переход с главной страницы к экскурсиям с дальнейшим оформлением одной из них (юзер-сценарий)\"\"\"\n        excursion_page = ExcursionPage(driver)\n        main_page = MainPage(driver)\n    \n        with allure.step(\"Открываем страницу\"):\n            driver.get(config.base_url)\n    \n        with allure.step(\"Переходим на страницу с экскурсиями\"):\n            driver.find_element(*main_page.all_excursion_btn).click()\n    \n        with allure.step(\"Переходим на страницу первой экскурсии списка\"):\n            first_excursion = main_page.excursions()[0]\n            first_excursion.click()\n    \n        # change the handle\n        excursion_page.move_last_handle()\n        page_url = driver.current_url\n    \n        # scroll to order button and click\n        order_button = driver.find_element(*excursion_page.order_button)\n        excursion_page.scroll_to(order_button)\n    \n        with allure.step(\"Кликаем на кнопку заказа\"):\n>           order_button.click()\n\ntests/test_excursium.py:66: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/webelement.py:120: in click\n    self._execute(Command.CLICK_ELEMENT)\n/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/webelement.py:573: in _execute\n    return self._parent.execute(command, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:454: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fb1cfc06710>\nresponse = {'status': 400, 'value': '{\"value\":{\"error\":\"element click intercepted\",\"message\":\"element click intercepted: Element ...\\\\n#22 0x5614760d4a4e \\\\u003Cunknown>\\\\n#23 0x5614760e59f5 \\\\u003Cunknown>\\\\n#24 0x7f01536431c4 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                try:\n                    value = json.loads(value_json)\n                    if isinstance(value, dict):\n                        if len(value) == 1:\n                            value = value[\"value\"]\n                        status = value.get(\"error\", None)\n                        if not status:\n                            status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                            message = value.get(\"value\") or value.get(\"message\")\n                            if not isinstance(message, str):\n                                value = message\n                                message = message.get(\"message\")\n                        else:\n                            message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (1439, -2090)\nE         (Session info: chrome=138.0.7204.168); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#elementclickinterceptedexception\nE       Stacktrace:\nE       #0 0x5614760e670e <unknown>\nE       #1 0x561475b82a51 <unknown>\nE       #2 0x561475bd3701 <unknown>\nE       #3 0x561475bd1cb9 <unknown>\nE       #4 0x561475bcf851 <unknown>\nE       #5 0x561475bcefe3 <unknown>\nE       #6 0x561475bc391a <unknown>\nE       #7 0x561475bf0ff2 <unknown>\nE       #8 0x561475bc30fd <unknown>\nE       #9 0x561475bf11be <unknown>\nE       #10 0x561475c10444 <unknown>\nE       #11 0x561475bf0dc3 <unknown>\nE       #12 0x561475bc1959 <unknown>\nE       #13 0x561475bc24c1 <unknown>\nE       #14 0x5614760b28aa <unknown>\nE       #15 0x5614760b5c11 <unknown>\nE       #16 0x5614760b56a8 <unknown>\nE       #17 0x5614760b60b5 <unknown>\nE       #18 0x56147609c34c <unknown>\nE       #19 0x5614760b6421 <unknown>\nE       #20 0x561476084e2a <unknown>\nE       #21 0x5614760d4855 <unknown>\nE       #22 0x5614760d4a4e <unknown>\nE       #23 0x5614760e59f5 <unknown>\nE       #24 0x7f01536431c4 <unknown>\n\n/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py:232: ElementClickInterceptedException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"driver","time":{"start":1753362226465,"stop":1753362226793,"duration":328},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"Переход с главной страницы к экскурсиям с дальнейшим оформлением одной из них (юзер-сценарий)","status":"broken","statusMessage":"selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (1439, -2090)\n  (Session info: chrome=138.0.7204.168); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#elementclickinterceptedexception\nStacktrace:\n#0 0x5614760e670e <unknown>\n#1 0x561475b82a51 <unknown>\n#2 0x561475bd3701 <unknown>\n#3 0x561475bd1cb9 <unknown>\n#4 0x561475bcf851 <unknown>\n#5 0x561475bcefe3 <unknown>\n#6 0x561475bc391a <unknown>\n#7 0x561475bf0ff2 <unknown>\n#8 0x561475bc30fd <unknown>\n#9 0x561475bf11be <unknown>\n#10 0x561475c10444 <unknown>\n#11 0x561475bf0dc3 <unknown>\n#12 0x561475bc1959 <unknown>\n#13 0x561475bc24c1 <unknown>\n#14 0x5614760b28aa <unknown>\n#15 0x5614760b5c11 <unknown>\n#16 0x5614760b56a8 <unknown>\n#17 0x5614760b60b5 <unknown>\n#18 0x56147609c34c <unknown>\n#19 0x5614760b6421 <unknown>\n#20 0x561476084e2a <unknown>\n#21 0x5614760d4855 <unknown>\n#22 0x5614760d4a4e <unknown>\n#23 0x5614760e59f5 <unknown>\n#24 0x7f01536431c4 <unknown>","statusTrace":"self = <test_excursium.TestUserCases object at 0x7fb1cfc04f50>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"a32448e15551abdbd4cd438c3c21f3d7\")>\n\n    @allure.title(\"Оформление экскурсии\")\n    @allure.severity(\"Critical\")\n    @pytest.mark.user_case\n    def test_order_excursion(self, driver):\n        \"\"\"Переход с главной страницы к экскурсиям с дальнейшим оформлением одной из них (юзер-сценарий)\"\"\"\n        excursion_page = ExcursionPage(driver)\n        main_page = MainPage(driver)\n    \n        with allure.step(\"Открываем страницу\"):\n            driver.get(config.base_url)\n    \n        with allure.step(\"Переходим на страницу с экскурсиями\"):\n            driver.find_element(*main_page.all_excursion_btn).click()\n    \n        with allure.step(\"Переходим на страницу первой экскурсии списка\"):\n            first_excursion = main_page.excursions()[0]\n            first_excursion.click()\n    \n        # change the handle\n        excursion_page.move_last_handle()\n        page_url = driver.current_url\n    \n        # scroll to order button and click\n        order_button = driver.find_element(*excursion_page.order_button)\n        excursion_page.scroll_to(order_button)\n    \n        with allure.step(\"Кликаем на кнопку заказа\"):\n>           order_button.click()\n\ntests/test_excursium.py:66: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/webelement.py:120: in click\n    self._execute(Command.CLICK_ELEMENT)\n/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/webelement.py:573: in _execute\n    return self._parent.execute(command, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:454: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fb1cfc06710>\nresponse = {'status': 400, 'value': '{\"value\":{\"error\":\"element click intercepted\",\"message\":\"element click intercepted: Element ...\\\\n#22 0x5614760d4a4e \\\\u003Cunknown>\\\\n#23 0x5614760e59f5 \\\\u003Cunknown>\\\\n#24 0x7f01536431c4 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                try:\n                    value = json.loads(value_json)\n                    if isinstance(value, dict):\n                        if len(value) == 1:\n                            value = value[\"value\"]\n                        status = value.get(\"error\", None)\n                        if not status:\n                            status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                            message = value.get(\"value\") or value.get(\"message\")\n                            if not isinstance(message, str):\n                                value = message\n                                message = message.get(\"message\")\n                        else:\n                            message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (1439, -2090)\nE         (Session info: chrome=138.0.7204.168); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#elementclickinterceptedexception\nE       Stacktrace:\nE       #0 0x5614760e670e <unknown>\nE       #1 0x561475b82a51 <unknown>\nE       #2 0x561475bd3701 <unknown>\nE       #3 0x561475bd1cb9 <unknown>\nE       #4 0x561475bcf851 <unknown>\nE       #5 0x561475bcefe3 <unknown>\nE       #6 0x561475bc391a <unknown>\nE       #7 0x561475bf0ff2 <unknown>\nE       #8 0x561475bc30fd <unknown>\nE       #9 0x561475bf11be <unknown>\nE       #10 0x561475c10444 <unknown>\nE       #11 0x561475bf0dc3 <unknown>\nE       #12 0x561475bc1959 <unknown>\nE       #13 0x561475bc24c1 <unknown>\nE       #14 0x5614760b28aa <unknown>\nE       #15 0x5614760b5c11 <unknown>\nE       #16 0x5614760b56a8 <unknown>\nE       #17 0x5614760b60b5 <unknown>\nE       #18 0x56147609c34c <unknown>\nE       #19 0x5614760b6421 <unknown>\nE       #20 0x561476084e2a <unknown>\nE       #21 0x5614760d4855 <unknown>\nE       #22 0x5614760d4a4e <unknown>\nE       #23 0x5614760e59f5 <unknown>\nE       #24 0x7f01536431c4 <unknown>\n\n/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py:232: ElementClickInterceptedException","steps":[{"name":"Открываем страницу","time":{"start":1753362226794,"stop":1753362230012,"duration":3218},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"Переходим на страницу с экскурсиями","time":{"start":1753362230012,"stop":1753362234061,"duration":4049},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"Переходим на страницу первой экскурсии списка","time":{"start":1753362234061,"stop":1753362234184,"duration":123},"status":"passed","steps":[{"name":"Получаем список экскурсий","time":{"start":1753362234061,"stop":1753362234076,"duration":15},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"Переходим на открытую вкладку","time":{"start":1753362234184,"stop":1753362234209,"duration":25},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"Скроллим до элемента","time":{"start":1753362237445,"stop":1753362240449,"duration":3004},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"Кликаем на кнопку заказа","time":{"start":1753362240449,"stop":1753362241506,"duration":1057},"status":"broken","statusMessage":"selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (1439, -2090)\n  (Session info: chrome=138.0.7204.168); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#elementclickinterceptedexception\nStacktrace:\n#0 0x5614760e670e <unknown>\n#1 0x561475b82a51 <unknown>\n#2 0x561475bd3701 <unknown>\n#3 0x561475bd1cb9 <unknown>\n#4 0x561475bcf851 <unknown>\n#5 0x561475bcefe3 <unknown>\n#6 0x561475bc391a <unknown>\n#7 0x561475bf0ff2 <unknown>\n#8 0x561475bc30fd <unknown>\n#9 0x561475bf11be <unknown>\n#10 0x561475c10444 <unknown>\n#11 0x561475bf0dc3 <unknown>\n#12 0x561475bc1959 <unknown>\n#13 0x561475bc24c1 <unknown>\n#14 0x5614760b28aa <unknown>\n#15 0x5614760b5c11 <unknown>\n#16 0x5614760b56a8 <unknown>\n#17 0x5614760b60b5 <unknown>\n#18 0x56147609c34c <unknown>\n#19 0x5614760b6421 <unknown>\n#20 0x561476084e2a <unknown>\n#21 0x5614760d4855 <unknown>\n#22 0x5614760d4a4e <unknown>\n#23 0x5614760e59f5 <unknown>\n#24 0x7f01536431c4 <unknown>\n\n","statusTrace":"  File \"/app/tests/test_excursium.py\", line 66, in test_order_excursion\n    order_button.click()\n    ~~~~~~~~~~~~~~~~~~^^\n  File \"/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/webelement.py\", line 120, in click\n    self._execute(Command.CLICK_ELEMENT)\n    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/webelement.py\", line 573, in _execute\n    return self._parent.execute(command, params)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 454, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[{"uid":"8d7e86fc1f58bf84","name":"Скриншот при падении","source":"8d7e86fc1f58bf84.png","type":"image/png","size":171750}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":7,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"driver::0","time":{"start":1753362241692,"stop":1753362241760,"duration":68},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"feature","value":"Пользовательские сценарии"},{"name":"severity","value":"Critical"},{"name":"tag","value":"user_case"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_excursium"},{"name":"subSuite","value":"TestUserCases"},{"name":"host","value":"767a3daa1a8d"},{"name":"thread","value":"19-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_excursium"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"critical","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["user_case"]},"source":"737e0c26c4146cf7.json","parameterValues":[]}